[package]
name = "async-graphql-relay"
description = "Relay support for async-graphql"
version = "0.4.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2018"
license = "MIT"

homepage = "https://github.com/oscartbeaumont/async-graphql-relay"
documentation = "https://docs.rs/async-graphql-relay"
repository = "https://github.com/oscartbeaumont/async-graphql-relay"
readme = "README.md"

keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]

[features]
with-sea-orm = ["sea-orm/uuid"]

[dependencies]
async-graphql = "3.0.17"
async-graphql-relay-derive = { path = "derive", version = "^0.4" }
async-trait = "0.1.52"
sea-orm = { git = "https://github.com/SeaQL/sea-orm.git", branch = "model-with-generics", default-features = false, optional = true } # TODO: We are using branch until changes are released
uuid = "0.8.2"

[dev-dependencies]
tokio = { version = "1.15.0", features = ["full"] }

[workspace]
members = [
    "derive",
    "example"
]
